oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone # or any uploader you use in the frontend
            storage:
                directory: "%kernel.project_dir%/public/uploads/doctors/clinics"