<?php


namespace App\Dictionnaires;


class FilterCity
{
    public const CITY = [
        "Meyrin",
        "Vernier",
        "Onex",
        "Plan-les-Ouates",
        "Lancy",
        "Le Grand-Saconnex",
        "Carouge",
        "Versoix",
        "Veyrier",
        "Chêne-Bougeries",
        "Thônex",
        "Nyon",
        "Gland",
        "Morges",
        "Ecublens",
        "Renens",
        "Prilly",
        "Lausanne",
        "Yverdon-les-Bains",
        "Pully",
        "Le Locle",
        "La Chaux-de-Fonds",
        "Vevey",
        "La Tour-de-Peilz",
        "Montreux",
        "Monthey",
        "Bulle",
        "Martigny",
        "Villars-sur-Glâne",
        "Biel/Bienne",
        "Lyss",
        "Delémont",
        "Sion",
        "Grenchen",
        "Köniz",
        "Ittigen",
        "Muri bei Bern",
        "Ostermundigen",
        "Bolligen",
        "Sierre",
        "Allschwil",
        "Oberwil",
        "Münsingen",
        "Binningen",
        "Basel",
        "Münchenstein",
        "Burgdorf",
        "Thun",
        "Birsfelden",
        "Riehen",
        "Steffisburg",
        "Muttenz",
        "Spiez",
        "Pratteln",
        "Herzogenbuchsee",
        "Liestal",
        "Langenthal",
        "Sumiswald",
        "Rheinfelden",
        "Visp",
        "Olten",
        "Oftringen",
        "Zofingen",
        "Bad Säckingen",
        "Brig",
        "Aarau",
        "Laufenburg",
        "Lenzburg",
        "Brugg",
        "Sarnen",
        "Mellingen",
        "Wohlen",
        "Kriens",
        "Emmen",
        "Baden",
        "Horw",
        "Wettingen",
        "Bremgarten",
        "Ebikon",
        "Stans",
        "Dietikon",
        "Rotkreuz",
        "Küssnacht",
        "Schlieren",
        "Affoltern am Albis",
        "Cham",
        "Regensdorf",
        "Arth",
        "Adliswil",
        "Baar",
        "Oberarth",
        "Bülach",
        "Goldau",
        "Thalwil",
        "Glattbrugg",
        "Opfikon",
        "Küsnacht",
        "Kloten",
        "Wallisellen",
        "Zollikon",
        "Horgen",
        "Dübendorf",
        "Neuhausen am Rheinfall",
        "Brüttisellen",
        "Meilen",
        "Wädenswil",
        "Effretikon",
        "Volketswil",
        "Richterswil",
        "Uster",
        "Illnau",
        "Winterthur",
        "Stäfa",
        "Einsiedeln",
        "Pfäffikon",
        "Locarno",
        "Wetzikon",
        "Rapperswil",
        "Jona",
        "Rüti",
        "Frauenfeld",
        "Gravesano",
        "Lugano",
        "Mendrisio",
        "Bellinzona",
        "Wil",
        "Wattwil",
        "Weinfelden",
        "Uzwil",
        "Kreuzlingen",
        "Münsterlingen",
        "Gossau",
        "Herisau",
        "Amriswil",
        "Engelburg",
        "St.Gallen",
        "Romanshorn",
        "Appenzell",
        "Arbon",
        "Buchs",
        "Chur",
        "Altstätten",
        "Davos",
        "Aargau",
        "Appenzell Ausserrhoden",
        "Appenzell Innerrhoden",
        "Basel-Landschaft",
        "Basel-Stadt",
        "Bern",
        "Fribourg",
        "Geneva",
        "Glarus",
        "Graubünden",
        "Jura",
        "Luzern",
        "Neuchâtel",
        "Nidwalden",
        "Obwalden",
        "Sankt Gallen",
        "Schwyz",
        "Schaffhausen",
        "Solothurn",
        "Thurgau",
        "Ticino",
        "Uri",
        "Valais",
        "Vaud",
        "Zug",
        "Zürich"
    ];
}