#index:
#    path: /
#    controller: App\Controller\IndexController::index

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

oneup_uploader:
    resource: .
    type: uploader


